apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-config
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  LOADBALANCEROPERATOR_EVENTS_NATS_SUBSCRIBEPREFIX: "{{ .Values.operator.events.topicPrefix }}"
  LOADBALANCEROPERATOR_EVENTS_NATS_URL: "{{ .Values.operator.events.connectionURL }}"
  LOADBALANCEROPERATOR_EVENTS_NATS_QUEUEGROUP: "{{ .Values.operator.events.queueGroup }}"
  LOADBALANCEROPERATOR_API_ENDPOINT: "{{ .Values.operator.api.endpoint }}"
  LOADBALANCEROPERATOR_CHART_PATH: "/chart.tgz"
  LOADBALANCEROPERATOR_CHART_VALUES_PATH: "/lb-values.yaml"
  LOADBALANCEROPERATOR_OIDC_CLIENT_ISSUER: "{{ .Values.operator.api.oidc.client.issuer }}"
{{- if .Values.operator.tracing.enabled }}
  LOADBALANCEROPERATOR_TRACING_ENABLED: "{{ .Values.operator.tracing.enabled }}"
  LOADBALANCEROPERATOR_TRACING_PROVIDER: "{{ .Values.operator.tracing.provider }}"
  LOADBALANCEROPERATOR_TRACING_ENVIRONMENT: "{{ .Values.operator.tracing.environment }}"
{{- if eq .Values.operator.tracing.provider "jaeger" }}
  LOADBALANCEROPERATOR_TRACING_JAEGER_ENDPOINT: "{{ .Values.operator.tracing.jaeger.endpoint }}"
  LOADBALANCEROPERATOR_TRACING_JAEGER_USER: "{{ .Values.operator.tracing.jaeger.user }}"
  LOADBALANCEROPERATOR_TRACING_JAEGER_PASSWORD: "{{ .Values.operator.tracing.jaeger.password }}"
{{- end }}
{{- if eq .Values.operator.tracing.provider "otlpgrpc" }}
  LOADBALANCEROPERATOR_TRACING_OTLP_ENDPOINT: "{{ .Values.operator.tracing.otlp.endpoint }}"
  LOADBALANCEROPERATOR_TRACING_OTLP_INSECURE: "{{ .Values.operator.tracing.otlp.insecure }}"
  LOADBALANCEROPERATOR_TRACING_OTLP_CERTIFICATE: "{{ .Values.operator.tracing.otlp.certificate }}"
{{- end }}
{{- end }}
